import type { AsiaLang } from "@/lib/asia-i18n";

const en = {
  headline: "How can we help you plan?", aboutHeadline: "Ask about {subject}",
  intro: "Start with a question or share details for a care plan in China.", free: "Free initial conversation",
  questionTitle: "Ask a question", questionDescription: "Just your contact details and question. No procedure choice needed.",
  carePlanTitle: "Get a care plan", carePlanDescription: "Share your procedure, budget, preferred city and travel timing. Not sure is fine.",
  questionIntro: "Tell us how to reply and what you would like to know.",
  carePlanIntro: "Share what you know so far. You can choose ‘Not sure yet’ for any planning detail.",
  contactMethod: "Preferred contact method", email: "Email", whatsapp: "WhatsApp", emailAddress: "Email address",
  phone: "WhatsApp number", phoneHint: "Include your country code, for example +44 7700 900123.",
  questionLabel: "Your question", questionPlaceholder: "What would you like to know?",
  procedure: "Procedure", procedureHint: "Enter a procedure or choose ‘Not sure yet’.",
  budget: "Procedure budget (USD)", city: "City in China", timing: "Travel timing", notSure: "Not sure yet",
  budgetOptions: ["Under $2,000", "$2,000–$5,000", "$5,000–$10,000", "Over $10,000"],
  timingOptions: ["Within 3 months", "In 3–6 months", "In 6–12 months", "More than a year away"],
  cities: ["Shanghai", "Beijing", "Guangzhou", "Hangzhou", "Hainan"],
  notes: "Questions or goals (optional)", back: "Change request type", continueEmail: "Continue by email", continueWhatsapp: "Continue on WhatsApp",
  handoffNote: "We’ll prepare a message. Review and send it in your email app or WhatsApp to contact us.",
  privacy: "These details stay in this form until you open your chosen app. Nothing is sent automatically.",
  ready: "Your message is ready", readyDescription: "Send the prepared message in your chosen app to contact CeladonChina. It has not been sent by this website.",
  reopenEmail: "Open email draft", reopenWhatsapp: "Open WhatsApp message", edit: "Edit my details", draft: "Review your message",
  openError: "We couldn’t open the app. Use the link below, or copy your message and send it to the contact shown.",
  emailError: "Enter an email address such as name@example.com.", phoneError: "Enter your WhatsApp number with a country code, starting with +.",
  questionError: "Enter the question you would like us to answer.", procedureError: "Enter a procedure or choose ‘Not sure yet’.",
  close: "Close", expert: "Expert", hospital: "Clinic or hospital", askExpert: "Ask about this expert",
  questionMessage: "Hi CeladonChina, I have a question about care in China.", carePlanMessage: "Hi CeladonChina, I would like help planning care in China.",
};

export type ConsultationPickerCopy = { [K in keyof typeof en]: (typeof en)[K] extends string[] ? string[] : string };

export const consultationPickerCopy: Record<AsiaLang, ConsultationPickerCopy> = {
  en,
  zh: {
    headline: "你希望从哪里开始？", aboutHeadline: "咨询{subject}", intro: "先问一个问题，或填写信息，规划在中国的就医行程。", free: "免费初步沟通",
    questionTitle: "问一个问题", questionDescription: "只需联系方式和问题，无需先选项目。", carePlanTitle: "获取就医规划", carePlanDescription: "填写项目、预算、意向城市和出行时间。不确定也没关系。",
    questionIntro: "留下回复方式，告诉我们你想了解什么。", carePlanIntro: "填写目前确定的信息。任何规划项都可以选择“尚未确定”。",
    contactMethod: "首选联系方式", email: "电子邮件", whatsapp: "WhatsApp", emailAddress: "邮箱地址", phone: "WhatsApp 号码", phoneHint: "请包含国家区号，例如 +86 138 0000 0000。",
    questionLabel: "你的问题", questionPlaceholder: "你想了解什么？", procedure: "项目", procedureHint: "输入项目名称，或选择“尚未确定”。", budget: "项目预算（美元）", city: "中国意向城市", timing: "出行时间", notSure: "尚未确定",
    budgetOptions: ["低于 $2,000", "$2,000–$5,000", "$5,000–$10,000", "高于 $10,000"], timingOptions: ["3个月内", "3–6个月后", "6–12个月后", "一年以后"], cities: ["上海", "北京", "广州", "杭州", "海南"],
    notes: "问题或目标（选填）", back: "更换咨询类型", continueEmail: "继续使用电子邮件", continueWhatsapp: "继续使用 WhatsApp",
    handoffNote: "我们会生成消息草稿。请在邮件应用或 WhatsApp 中检查并发送，才能联系我们。", privacy: "打开所选应用前，信息仅保留在当前表单中，不会自动发送。",
    ready: "消息草稿已准备好", readyDescription: "请在所选应用中发送草稿，联系 CeladonChina。本网站尚未发送你的消息。", reopenEmail: "打开邮件草稿", reopenWhatsapp: "打开 WhatsApp 消息", edit: "修改信息", draft: "检查消息内容",
    openError: "未能打开应用。请使用下方链接，或复制消息并发送到所示联系方式。", emailError: "请填写邮箱地址，例如 name@example.com。", phoneError: "请填写包含国家区号的 WhatsApp 号码，以 + 开头。", questionError: "请填写你希望我们解答的问题。", procedureError: "请填写项目，或选择“尚未确定”。",
    close: "关闭", expert: "专家", hospital: "诊所或医院", askExpert: "咨询这位专家", questionMessage: "你好 CeladonChina，我想咨询在中国就医的问题。", carePlanMessage: "你好 CeladonChina，我希望获得中国就医规划协助。",
  },
  ru: {
    headline: "С чего начнём?", aboutHeadline: "Узнать о {subject}", intro: "Задайте вопрос или расскажите о планах на лечение в Китае.", free: "Первое общение бесплатно",
    questionTitle: "Задать вопрос", questionDescription: "Только контакт и вопрос. Выбирать процедуру не нужно.", carePlanTitle: "Получить план поездки", carePlanDescription: "Укажите процедуру, бюджет, город и сроки. Можно ответить «Пока не знаю».",
    questionIntro: "Укажите, как вам ответить, и задайте вопрос.", carePlanIntro: "Расскажите, что уже решили. В любом пункте можно выбрать «Пока не знаю».",
    contactMethod: "Предпочтительный способ связи", email: "Электронная почта", whatsapp: "WhatsApp", emailAddress: "Адрес электронной почты", phone: "Номер WhatsApp", phoneHint: "Укажите код страны, например +7 912 3456789.",
    questionLabel: "Ваш вопрос", questionPlaceholder: "Что вы хотите узнать?", procedure: "Процедура", procedureHint: "Введите процедуру или выберите «Пока не знаю».", budget: "Бюджет на процедуру (USD)", city: "Город в Китае", timing: "Сроки поездки", notSure: "Пока не знаю",
    budgetOptions: ["До $2,000", "$2,000–$5,000", "$5,000–$10,000", "Более $10,000"], timingOptions: ["В течение 3 месяцев", "Через 3–6 месяцев", "Через 6–12 месяцев", "Более чем через год"], cities: ["Шанхай", "Пекин", "Гуанчжоу", "Ханчжоу", "Хайнань"],
    notes: "Вопросы или цели (необязательно)", back: "Изменить тип обращения", continueEmail: "Продолжить по почте", continueWhatsapp: "Продолжить в WhatsApp",
    handoffNote: "Мы подготовим сообщение. Проверьте и отправьте его в почтовом приложении или WhatsApp.", privacy: "Данные остаются в форме до открытия приложения. Ничего не отправляется автоматически.",
    ready: "Сообщение подготовлено", readyDescription: "Отправьте сообщение в выбранном приложении, чтобы связаться с CeladonChina. Сайт ещё не отправил его.", reopenEmail: "Открыть черновик письма", reopenWhatsapp: "Открыть сообщение WhatsApp", edit: "Изменить данные", draft: "Проверить сообщение",
    openError: "Не удалось открыть приложение. Нажмите ссылку ниже или скопируйте сообщение и отправьте по указанному контакту.", emailError: "Введите адрес почты, например name@example.com.", phoneError: "Введите номер WhatsApp с кодом страны, начиная с +.", questionError: "Введите вопрос, на который вы хотите получить ответ.", procedureError: "Введите процедуру или выберите «Пока не знаю».",
    close: "Закрыть", expert: "Эксперт", hospital: "Клиника или больница", askExpert: "Спросить об эксперте", questionMessage: "Здравствуйте, CeladonChina! У меня вопрос о лечении в Китае.", carePlanMessage: "Здравствуйте, CeladonChina! Мне нужна помощь с планированием лечения в Китае.",
  },
  es: {
    headline: "¿Por dónde quieres empezar?", aboutHeadline: "Pregunta sobre {subject}", intro: "Haz una pregunta o comparte tus preferencias para planificar tu atención en China.", free: "Primera conversación gratuita",
    questionTitle: "Hacer una pregunta", questionDescription: "Solo tu contacto y tu pregunta. No necesitas elegir un procedimiento.", carePlanTitle: "Obtener un plan de atención", carePlanDescription: "Indica procedimiento, presupuesto, ciudad y fechas. Puedes elegir «Aún no lo sé».",
    questionIntro: "Dinos cómo responderte y qué te gustaría saber.", carePlanIntro: "Comparte lo que ya sabes. Puedes elegir «Aún no lo sé» en cualquier detalle del plan.",
    contactMethod: "Medio de contacto preferido", email: "Correo electrónico", whatsapp: "WhatsApp", emailAddress: "Dirección de correo electrónico", phone: "Número de WhatsApp", phoneHint: "Incluye el prefijo del país, por ejemplo +34 612 345678.",
    questionLabel: "Tu pregunta", questionPlaceholder: "¿Qué te gustaría saber?", procedure: "Procedimiento", procedureHint: "Escribe un procedimiento o elige «Aún no lo sé».", budget: "Presupuesto del procedimiento (USD)", city: "Ciudad en China", timing: "Fechas del viaje", notSure: "Aún no lo sé",
    budgetOptions: ["Menos de $2,000", "$2,000–$5,000", "$5,000–$10,000", "Más de $10,000"], timingOptions: ["En los próximos 3 meses", "En 3–6 meses", "En 6–12 meses", "Dentro de más de un año"], cities: ["Shanghái", "Pekín", "Cantón", "Hangzhou", "Hainan"],
    notes: "Preguntas u objetivos (opcional)", back: "Cambiar tipo de solicitud", continueEmail: "Continuar por correo", continueWhatsapp: "Continuar en WhatsApp",
    handoffNote: "Prepararemos un mensaje. Revísalo y envíalo desde tu correo o WhatsApp para contactarnos.", privacy: "Los datos permanecen en este formulario hasta que abras la aplicación. Nada se envía automáticamente.",
    ready: "Tu mensaje está preparado", readyDescription: "Envía el mensaje desde la aplicación elegida para contactar con CeladonChina. Este sitio aún no lo ha enviado.", reopenEmail: "Abrir borrador del correo", reopenWhatsapp: "Abrir mensaje de WhatsApp", edit: "Editar mis datos", draft: "Revisar tu mensaje",
    openError: "No pudimos abrir la aplicación. Usa el enlace o copia el mensaje y envíalo al contacto indicado.", emailError: "Introduce un correo, por ejemplo name@example.com.", phoneError: "Introduce tu número de WhatsApp con el prefijo del país, empezando por +.", questionError: "Escribe la pregunta que quieres que respondamos.", procedureError: "Introduce un procedimiento o elige «Aún no lo sé».",
    close: "Cerrar", expert: "Experto", hospital: "Clínica u hospital", askExpert: "Preguntar sobre este experto", questionMessage: "Hola, CeladonChina. Tengo una pregunta sobre la atención en China.", carePlanMessage: "Hola, CeladonChina. Me gustaría recibir ayuda para planificar mi atención en China.",
  },
  th: {
    headline: "คุณอยากเริ่มจากตรงไหน?", aboutHeadline: "สอบถามเกี่ยวกับ {subject}", intro: "เริ่มจากคำถาม หรือแจ้งรายละเอียดเพื่อวางแผนรับบริการในจีน", free: "พูดคุยเบื้องต้นฟรี",
    questionTitle: "สอบถาม", questionDescription: "กรอกเพียงข้อมูลติดต่อและคำถาม ยังไม่ต้องเลือกหัตถการ", carePlanTitle: "ขอแผนการดูแล", carePlanDescription: "แจ้งหัตถการ งบประมาณ เมืองและช่วงเดินทาง หากยังไม่ทราบก็เลือกได้",
    questionIntro: "แจ้งช่องทางรับคำตอบและสิ่งที่คุณอยากทราบ", carePlanIntro: "กรอกข้อมูลที่ทราบแล้ว คุณเลือก “ยังไม่แน่ใจ” ได้ในทุกหัวข้อของแผน",
    contactMethod: "ช่องทางติดต่อที่ต้องการ", email: "อีเมล", whatsapp: "WhatsApp", emailAddress: "ที่อยู่อีเมล", phone: "หมายเลข WhatsApp", phoneHint: "ระบุรหัสประเทศด้วย เช่น +66 81 234 5678",
    questionLabel: "คำถามของคุณ", questionPlaceholder: "คุณอยากทราบอะไร?", procedure: "หัตถการ", procedureHint: "กรอกชื่อหัตถการหรือเลือก “ยังไม่แน่ใจ”", budget: "งบประมาณหัตถการ (USD)", city: "เมืองในจีน", timing: "ช่วงเวลาเดินทาง", notSure: "ยังไม่แน่ใจ",
    budgetOptions: ["ต่ำกว่า $2,000", "$2,000–$5,000", "$5,000–$10,000", "มากกว่า $10,000"], timingOptions: ["ภายใน 3 เดือน", "ในอีก 3–6 เดือน", "ในอีก 6–12 เดือน", "อีกมากกว่าหนึ่งปี"], cities: ["เซี่ยงไฮ้", "ปักกิ่ง", "กว่างโจว", "หางโจว", "ไห่หนาน"],
    notes: "คำถามหรือเป้าหมาย (ไม่บังคับ)", back: "เปลี่ยนประเภทคำขอ", continueEmail: "ดำเนินการต่อทางอีเมล", continueWhatsapp: "ดำเนินการต่อใน WhatsApp",
    handoffNote: "เราจะเตรียมข้อความให้คุณ โปรดตรวจสอบและส่งในแอปอีเมลหรือ WhatsApp เพื่อติดต่อเรา", privacy: "ข้อมูลอยู่ในแบบฟอร์มนี้จนกว่าคุณจะเปิดแอปที่เลือก ไม่มีการส่งโดยอัตโนมัติ",
    ready: "เตรียมข้อความพร้อมแล้ว", readyDescription: "ส่งข้อความในแอปที่เลือกเพื่อติดต่อ CeladonChina เว็บไซต์นี้ยังไม่ได้ส่งข้อความของคุณ", reopenEmail: "เปิดอีเมลฉบับร่าง", reopenWhatsapp: "เปิดข้อความ WhatsApp", edit: "แก้ไขข้อมูล", draft: "ตรวจสอบข้อความ",
    openError: "เปิดแอปไม่สำเร็จ ใช้ลิงก์ด้านล่าง หรือคัดลอกข้อความแล้วส่งไปยังช่องทางที่แสดง", emailError: "กรอกอีเมล เช่น name@example.com", phoneError: "กรอกหมายเลข WhatsApp พร้อมรหัสประเทศ โดยเริ่มด้วย +", questionError: "กรอกคำถามที่คุณต้องการให้เราตอบ", procedureError: "กรอกหัตถการหรือเลือก “ยังไม่แน่ใจ”",
    close: "ปิด", expert: "ผู้เชี่ยวชาญ", hospital: "คลินิกหรือโรงพยาบาล", askExpert: "สอบถามเกี่ยวกับผู้เชี่ยวชาญคนนี้", questionMessage: "สวัสดี CeladonChina ฉันมีคำถามเกี่ยวกับการรับบริการในจีน", carePlanMessage: "สวัสดี CeladonChina ฉันต้องการความช่วยเหลือในการวางแผนรับบริการในจีน",
  },
  ms: {
    headline: "Di mana anda mahu bermula?", aboutHeadline: "Tanya tentang {subject}", intro: "Tanya soalan atau kongsi butiran untuk merancang penjagaan anda di China.", free: "Perbualan awal percuma",
    questionTitle: "Tanya soalan", questionDescription: "Hanya butiran hubungan dan soalan anda. Tidak perlu memilih prosedur.", carePlanTitle: "Dapatkan pelan penjagaan", carePlanDescription: "Kongsi prosedur, bajet, bandar dan masa perjalanan. Boleh pilih “Belum pasti”.",
    questionIntro: "Beritahu cara untuk membalas dan apa yang anda ingin tahu.", carePlanIntro: "Kongsi perkara yang sudah anda ketahui. Anda boleh memilih “Belum pasti” untuk setiap butiran pelan.",
    contactMethod: "Kaedah hubungan pilihan", email: "E-mel", whatsapp: "WhatsApp", emailAddress: "Alamat e-mel", phone: "Nombor WhatsApp", phoneHint: "Sertakan kod negara, contohnya +60 12 345 6789.",
    questionLabel: "Soalan anda", questionPlaceholder: "Apa yang anda ingin tahu?", procedure: "Prosedur", procedureHint: "Masukkan prosedur atau pilih “Belum pasti”.", budget: "Bajet prosedur (USD)", city: "Bandar di China", timing: "Masa perjalanan", notSure: "Belum pasti",
    budgetOptions: ["Bawah $2,000", "$2,000–$5,000", "$5,000–$10,000", "Melebihi $10,000"], timingOptions: ["Dalam 3 bulan", "Dalam 3–6 bulan", "Dalam 6–12 bulan", "Lebih daripada setahun lagi"], cities: ["Shanghai", "Beijing", "Guangzhou", "Hangzhou", "Hainan"],
    notes: "Soalan atau matlamat (pilihan)", back: "Tukar jenis permintaan", continueEmail: "Teruskan melalui e-mel", continueWhatsapp: "Teruskan di WhatsApp",
    handoffNote: "Kami akan menyediakan mesej. Semak dan hantar dalam aplikasi e-mel atau WhatsApp untuk menghubungi kami.", privacy: "Butiran kekal dalam borang ini sehingga anda membuka aplikasi pilihan. Tiada apa dihantar secara automatik.",
    ready: "Mesej anda sudah disediakan", readyDescription: "Hantar mesej dalam aplikasi pilihan untuk menghubungi CeladonChina. Laman ini belum menghantarnya.", reopenEmail: "Buka draf e-mel", reopenWhatsapp: "Buka mesej WhatsApp", edit: "Edit butiran saya", draft: "Semak mesej anda",
    openError: "Aplikasi tidak dapat dibuka. Gunakan pautan di bawah atau salin mesej dan hantar ke hubungan yang dipaparkan.", emailError: "Masukkan alamat e-mel seperti name@example.com.", phoneError: "Masukkan nombor WhatsApp dengan kod negara, bermula dengan +.", questionError: "Masukkan soalan yang anda mahu kami jawab.", procedureError: "Masukkan prosedur atau pilih “Belum pasti”.",
    close: "Tutup", expert: "Pakar", hospital: "Klinik atau hospital", askExpert: "Tanya tentang pakar ini", questionMessage: "Hai CeladonChina, saya ada soalan tentang penjagaan di China.", carePlanMessage: "Hai CeladonChina, saya ingin bantuan merancang penjagaan di China.",
  },
};

export const getConsultationPickerCopy = (lang: AsiaLang) => consultationPickerCopy[lang];
export const withConsultationSubject = (template: string, subject: string) => template.replace("{subject}", subject);
