import type { AsiaLang } from "@/lib/asia-i18n";

type VideoControlsCopy = { play: string; pause: string; mute: string; unmute: string; share: string; copied: string; shared: string; manualCopy: string; copyLink: string; close: string; failed: string; previous: string; next: string };
export const videoControlsCopy: Record<AsiaLang, VideoControlsCopy> = {
  en: { play: "Play video", pause: "Pause video", mute: "Mute video", unmute: "Unmute video", share: "Share this case", copied: "Link copied", shared: "Share completed", manualCopy: "Copy the link below to share this case.", copyLink: "Case link", close: "Close", failed: "Video could not play. Try again or open the case.", previous: "Previous video", next: "Next video" },
  zh: { play: "播放视频", pause: "暂停视频", mute: "视频静音", unmute: "开启视频声音", share: "分享此案例", copied: "链接已复制", shared: "已完成分享", manualCopy: "复制下方链接，即可分享此案例。", copyLink: "案例链接", close: "关闭", failed: "视频暂时无法播放，请重试或打开案例。", previous: "上一个视频", next: "下一个视频" },
  ru: { play: "Воспроизвести видео", pause: "Приостановить видео", mute: "Выключить звук", unmute: "Включить звук", share: "Поделиться случаем", copied: "Ссылка скопирована", shared: "Отправлено", manualCopy: "Скопируйте ссылку ниже, чтобы поделиться.", copyLink: "Ссылка на случай", close: "Закрыть", failed: "Не удалось воспроизвести видео. Повторите попытку или откройте случай.", previous: "Предыдущее видео", next: "Следующее видео" },
  es: { play: "Reproducir video", pause: "Pausar video", mute: "Silenciar video", unmute: "Activar sonido", share: "Compartir este caso", copied: "Enlace copiado", shared: "Compartido", manualCopy: "Copia el enlace de abajo para compartir este caso.", copyLink: "Enlace del caso", close: "Cerrar", failed: "No se pudo reproducir el video. Reintenta o abre el caso.", previous: "Video anterior", next: "Siguiente video" },
  th: { play: "เล่นวิดีโอ", pause: "หยุดวิดีโอชั่วคราว", mute: "ปิดเสียงวิดีโอ", unmute: "เปิดเสียงวิดีโอ", share: "แชร์กรณีนี้", copied: "คัดลอกลิงก์แล้ว", shared: "แชร์แล้ว", manualCopy: "คัดลอกลิงก์ด้านล่างเพื่อแชร์กรณีนี้", copyLink: "ลิงก์กรณี", close: "ปิด", failed: "เล่นวิดีโอไม่ได้ โปรดลองอีกครั้งหรือเปิดกรณีนี้", previous: "วิดีโอก่อนหน้า", next: "วิดีโอถัดไป" },
  ms: { play: "Mainkan video", pause: "Jeda video", mute: "Senyapkan video", unmute: "Hidupkan bunyi video", share: "Kongsi kes ini", copied: "Pautan disalin", shared: "Dikongsi", manualCopy: "Salin pautan di bawah untuk berkongsi kes ini.", copyLink: "Pautan kes", close: "Tutup", failed: "Video tidak dapat dimainkan. Cuba lagi atau buka kes.", previous: "Video sebelumnya", next: "Video seterusnya" },
};
