project_id = "vczghaemqtmsxvgtvbah"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false

  [functions.process-email-queue]
    verify_jwt = true

  [functions.quote-notification]
    verify_jwt = false
