import type { AsiaLang } from "@/lib/asia-i18n";

/** Vietnamese is optional here: asiaCopy() falls back to English until these strings are translated. */
export type ClinicCopy = Record<Exclude<AsiaLang, "vi">, string> & { vi?: string };

export const clinicProfileCopy = {
  title: { en: "Compare this institution", zh: "了解并比较这家机构", ru: "Сведения для сравнения", es: "Compara este centro", th: "ข้อมูลสำหรับเปรียบเทียบสถานพยาบาล", ms: "Bandingkan institusi ini" },
  introduction: { en: "Details below come from the linked public sources. Confirm the current services, doctor and campus before booking.", zh: "以下信息来自所列公开来源。预约前请确认当前服务、医生及就诊院区。", ru: "Сведения ниже взяты из указанных открытых источников. Перед записью уточните услуги, врача и место приёма.", es: "Los datos proceden de las fuentes públicas enlazadas. Confirma los servicios, el médico y la sede antes de reservar.", th: "ข้อมูลด้านล่างมาจากแหล่งข้อมูลสาธารณะที่แนบไว้ โปรดยืนยันบริการ แพทย์ และสถานที่ก่อนนัดหมาย", ms: "Maklumat di bawah diperoleh daripada sumber awam yang dipautkan. Sahkan perkhidmatan, doktor dan lokasi sebelum membuat janji temu." },
  services: { en: "Published service areas", zh: "公开列示的服务方向", ru: "Опубликованные направления", es: "Servicios publicados", th: "บริการที่เผยแพร่", ms: "Bidang perkhidmatan yang diterbitkan" },
  servicesNote: { en: "These are source-listed departments, not confirmation that every procedure is currently available.", zh: "这些是来源列示的科室方向，不代表每项手术当前均可预约。", ru: "Это направления из источника, а не подтверждение текущей доступности каждой процедуры.", es: "Son áreas indicadas en las fuentes, no una confirmación de que todos los procedimientos estén disponibles actualmente.", th: "นี่คือแผนกที่ระบุในแหล่งข้อมูล ไม่ใช่การยืนยันว่าหัตถการทุกรายการพร้อมให้บริการในขณะนี้", ms: "Ini ialah jabatan yang disenaraikan dalam sumber, bukan pengesahan bahawa setiap prosedur tersedia pada masa ini." },
  servicesMissing: { en: "Service details have not been confirmed from a current official source. Ask the institution about your procedure.", zh: "尚未从当前官方来源确认具体服务，请向机构咨询您关注的项目。", ru: "Актуальный официальный перечень услуг не подтверждён. Уточните нужную процедуру в учреждении.", es: "No hemos confirmado los servicios en una fuente oficial actual. Consulta tu procedimiento con el centro.", th: "ยังไม่ได้ยืนยันรายละเอียดบริการจากแหล่งข้อมูลทางการปัจจุบัน โปรดสอบถามสถานพยาบาลเกี่ยวกับหัตถการที่สนใจ", ms: "Butiran perkhidmatan belum disahkan melalui sumber rasmi semasa. Tanya institusi tentang prosedur anda." },
  servicesLink: { en: "View the service information source", zh: "查看服务信息来源", ru: "Источник сведений об услугах", es: "Ver la fuente de los servicios", th: "ดูแหล่งข้อมูลบริการ", ms: "Lihat sumber maklumat perkhidmatan" },
  doctors: { en: "Doctor information", zh: "医生信息", ru: "Информация о врачах", es: "Información de médicos", th: "ข้อมูลแพทย์", ms: "Maklumat doktor" },
  doctorsLink: { en: "View the official doctor directory / schedule", zh: "查看官方医生目录／出诊安排", ru: "Официальный список врачей / расписание", es: "Ver el directorio / horario oficial", th: "ดูรายชื่อแพทย์ / ตารางออกตรวจทางการ", ms: "Lihat direktori / jadual doktor rasmi" },
  doctorsNote: { en: "This external directory is separate from profiles published on CeladonChina. Confirm the doctor's current campus and availability.", zh: "该外部目录与 CeladonChina 已发布的医生资料不同。请确认医生当前就诊院区及可预约时间。", ru: "Этот внешний каталог не связан с профилями CeladonChina. Уточните текущее место и время приёма врача.", es: "Este directorio externo es independiente de los perfiles de CeladonChina. Confirma la sede y disponibilidad del médico.", th: "รายชื่อภายนอกนี้แยกจากโปรไฟล์บน CeladonChina โปรดยืนยันสถานที่และเวลาที่แพทย์พร้อมให้บริการ", ms: "Direktori luar ini berasingan daripada profil di CeladonChina. Sahkan lokasi dan ketersediaan doktor." },
  doctorsMissing: { en: "A current official doctor directory has not been confirmed. Ask the institution for the proposed doctor's name, qualifications and practice location.", zh: "尚未确认可用的当前官方医生目录。请向机构索取拟接诊医生的姓名、资质与执业地点。", ru: "Актуальный официальный список врачей не подтверждён. Запросите имя, квалификацию и место практики предлагаемого врача.", es: "No hemos confirmado un directorio oficial actual. Pide al centro el nombre, la formación y el lugar de consulta del médico propuesto.", th: "ยังไม่ได้ยืนยันรายชื่อแพทย์ทางการปัจจุบัน โปรดขอชื่อ คุณสมบัติ และสถานที่ปฏิบัติงานของแพทย์จากสถานพยาบาล", ms: "Direktori doktor rasmi semasa belum disahkan. Minta nama, kelayakan dan lokasi amalan doktor yang dicadangkan daripada institusi." },
  campus: { en: "Campus & address", zh: "院区与地址", ru: "Место приёма и адрес", es: "Sede y dirección", th: "สถานที่และที่อยู่", ms: "Lokasi dan alamat" },
  campusMissing: { en: "The exact current campus address has not been confirmed. Get written appointment details before travelling.", zh: "尚未确认当前具体院区地址。出行前请获取书面预约信息。", ru: "Точный актуальный адрес не подтверждён. До поездки получите письменное подтверждение места приёма.", es: "No hemos confirmado la dirección actual de la sede. Obtén los detalles de la cita por escrito antes de viajar.", th: "ยังไม่ได้ยืนยันที่อยู่ปัจจุบันที่แน่นอน โปรดรับรายละเอียดการนัดหมายเป็นลายลักษณ์อักษรก่อนเดินทาง", ms: "Alamat lokasi semasa yang tepat belum disahkan. Dapatkan butiran janji temu secara bertulis sebelum perjalanan." },
  campusLink: { en: "View address source", zh: "查看地址来源", ru: "Источник адреса", es: "Ver la fuente de la dirección", th: "ดูแหล่งข้อมูลที่อยู่", ms: "Lihat sumber alamat" },
  campusNote: { en: "This is the address stated in the source, not confirmation of your appointment location. Confirm the exact campus, building and entrance before travelling.", zh: "这是来源中列示的地址，并非您的预约地点确认。出行前请确认具体院区、楼栋及入口。", ru: "Это адрес из источника, а не подтверждение места вашей записи. Перед поездкой уточните корпус, здание и вход.", es: "Es la dirección indicada en la fuente, no la confirmación de tu lugar de cita. Confirma la sede, el edificio y la entrada antes de viajar.", th: "นี่คือที่อยู่ตามแหล่งข้อมูล ไม่ใช่การยืนยันสถานที่นัดหมายของคุณ โปรดยืนยันสถานที่ อาคาร และทางเข้าก่อนเดินทาง", ms: "Ini ialah alamat yang dinyatakan dalam sumber, bukan pengesahan lokasi janji temu anda. Sahkan lokasi, bangunan dan pintu masuk sebelum perjalanan." },
  language: { en: "Institution language support", zh: "机构提供的语言支持", ru: "Языковая поддержка учреждения", es: "Asistencia lingüística del centro", th: "การช่วยเหลือด้านภาษาของสถานพยาบาล", ms: "Sokongan bahasa institusi" },
  languageMissing: { en: "Hospital-provided language support is not confirmed in the reviewed sources. Ask the hospital which languages its doctors speak, whether it provides interpreters and whether it charges for them.", zh: "所查来源中尚未确认医院自有的语言支持。请向医院询问医生可使用的语言、院方是否提供口译及院方的收费情况。", ru: "Языковая поддержка самой больницы не подтверждена в изученных источниках. Уточните в больнице языки врачей, наличие переводчиков от больницы и стоимость их услуг.", es: "Las fuentes revisadas no confirman la asistencia lingüística del hospital. Pregunta al hospital qué idiomas hablan sus médicos, si proporciona intérpretes y si cobra por ellos.", th: "แหล่งข้อมูลที่ตรวจสอบยังไม่ยืนยันบริการภาษาของโรงพยาบาล โปรดสอบถามโรงพยาบาลเกี่ยวกับภาษาที่แพทย์ใช้ บริการล่ามของโรงพยาบาล และค่าบริการ", ms: "Sokongan bahasa yang disediakan oleh hospital belum disahkan dalam sumber yang disemak. Tanya hospital tentang bahasa yang digunakan doktornya, jurubahasa yang disediakan dan caj perkhidmatan tersebut." },
  celadonLanguage: { en: "CeladonChina interpretation arrangements follow your agreed support plan. Confirm your required language and visits with our team first.", zh: "CeladonChina 的口译安排以双方确认的支持方案为准，请先与团队确认所需语言和就诊安排。", ru: "Организация перевода CeladonChina зависит от согласованного плана поддержки. Сначала уточните с нашей командой нужный язык и посещения.", es: "La interpretación de CeladonChina se organiza según el plan de apoyo acordado. Confirma primero con nuestro equipo el idioma y las visitas que necesitas.", th: "การจัดล่ามของ CeladonChina เป็นไปตามแผนช่วยเหลือที่ตกลงกัน โปรดยืนยันภาษาและการเข้ารับบริการที่ต้องการกับทีมของเราก่อน", ms: "Urusan jurubahasa CeladonChina mengikut pelan sokongan yang dipersetujui. Sahkan dahulu bahasa dan lawatan yang diperlukan dengan pasukan kami." },
  celadonLanguageLink: { en: "View CeladonChina support", zh: "查看 CeladonChina 支持服务", ru: "Поддержка CeladonChina", es: "Ver el apoyo de CeladonChina", th: "ดูบริการช่วยเหลือของ CeladonChina", ms: "Lihat sokongan CeladonChina" },
  reviewDate: { en: "Sources reviewed on", zh: "来源查阅日期", ru: "Источники просмотрены", es: "Fuentes revisadas el", th: "วันที่ตรวจสอบแหล่งข้อมูล", ms: "Tarikh sumber disemak" },
  reviewNote: { en: "A source review is not a licence audit, clinical assessment or confirmation of a CeladonChina partnership.", zh: "查阅公开来源不等于执照审核、医疗评估或确认与 CeladonChina 的合作关系。", ru: "Просмотр источников не является проверкой лицензии, клинической оценкой или подтверждением партнёрства с CeladonChina.", es: "Revisar fuentes no equivale a auditar licencias, evaluar la atención clínica ni confirmar una colaboración con CeladonChina.", th: "การตรวจสอบแหล่งข้อมูลไม่ใช่การตรวจสอบใบอนุญาต การประเมินทางคลินิก หรือการยืนยันความร่วมมือกับ CeladonChina", ms: "Semakan sumber bukan audit lesen, penilaian klinikal atau pengesahan kerjasama dengan CeladonChina." },
  inquiry: { en: "Ask about these details", zh: "咨询这些信息", ru: "Уточнить эти сведения", es: "Consultar estos detalles", th: "สอบถามรายละเอียดเหล่านี้", ms: "Tanya tentang butiran ini" },
  sourceLanguage: { en: "Chinese-language source", zh: "中文来源", ru: "Источник на китайском", es: "Fuente en chino", th: "แหล่งข้อมูลภาษาจีน", ms: "Sumber bahasa Cina" },
} satisfies Record<string, ClinicCopy>;

export const clinicServiceNames = {
  surgery: { en: "Cosmetic surgery", zh: "美容外科", ru: "Эстетическая хирургия", es: "Cirugía estética", th: "ศัลยกรรมความงาม", ms: "Pembedahan kosmetik" },
  dermatology: { en: "Cosmetic dermatology", zh: "美容皮肤科", ru: "Эстетическая дерматология", es: "Dermatología estética", th: "ผิวหนังเพื่อความงาม", ms: "Dermatologi kosmetik" },
  eyes: { en: "Eye procedures", zh: "眼部整形", ru: "Коррекция области глаз", es: "Procedimientos de ojos", th: "ศัลยกรรมรอบดวงตา", ms: "Prosedur mata" },
  nose: { en: "Nose surgery", zh: "鼻部整形", ru: "Пластика носа", es: "Cirugía de nariz", th: "ศัลยกรรมจมูก", ms: "Pembedahan hidung" },
  breast: { en: "Breast procedures", zh: "乳房整形", ru: "Пластика груди", es: "Procedimientos de pecho", th: "ศัลยกรรมเต้านม", ms: "Prosedur payudara" },
  body: { en: "Body contouring", zh: "身体塑形", ru: "Коррекция контуров тела", es: "Contorno corporal", th: "การปรับรูปร่าง", ms: "Pembentukan badan" },
  facial: { en: "Face & neck surgery", zh: "面颈部整形", ru: "Пластика лица и шеи", es: "Cirugía de cara y cuello", th: "ศัลยกรรมใบหน้าและลำคอ", ms: "Pembedahan muka dan leher" },
  fat: { en: "Fat surgery", zh: "脂肪整形", ru: "Операции на жировой ткани", es: "Cirugía de tejido adiposo", th: "ศัลยกรรมไขมัน", ms: "Pembedahan lemak" },
  scars: { en: "Scar & wound care", zh: "瘢痕与创面修复", ru: "Лечение рубцов и ран", es: "Atención de cicatrices y heridas", th: "การดูแลแผลเป็นและบาดแผล", ms: "Penjagaan parut dan luka" },
  laser: { en: "Laser services", zh: "激光治疗", ru: "Лазерные процедуры", es: "Servicios de láser", th: "บริการเลเซอร์", ms: "Perkhidmatan laser" },
  injections: { en: "Injectable treatments", zh: "注射美容", ru: "Инъекционные процедуры", es: "Tratamientos inyectables", th: "หัตถการฉีด", ms: "Rawatan suntikan" },
  hair: { en: "Hair transplantation", zh: "毛发移植", ru: "Пересадка волос", es: "Trasplante capilar", th: "การปลูกผม", ms: "Pemindahan rambut" },
  dental: { en: "Aesthetic dentistry", zh: "口腔美容", ru: "Эстетическая стоматология", es: "Odontología estética", th: "ทันตกรรมเพื่อความงาม", ms: "Pergigian estetik" },
} satisfies Record<string, ClinicCopy>;
