import { useEffect, useState } from "react";
import { Link, Navigate } from "react-router-dom";
import { ArrowLeft, Loader2, Stethoscope, Trash2, UploadCloud } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/lib/auth";
import { supabase } from "@/integrations/supabase/client";
import { signedUrls } from "@/lib/storage-urls";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
type Doctor={id:string;name:string;title:string;hospital:string;city:string;specialties:string[];bio:string;credentials:string|null;photo_path:string|null;status:string;photoUrl?:string};
const ADMIN="shijieyuwork@gmail.com";
export default function DoctorAdmin(){const{user,loading:authLoading}=useAuth();const[doctors,setDoctors]=useState<Doctor[]>([]);const[busy,setBusy]=useState(false);const[photo,setPhoto]=useState<File|null>(null);const[name,setName]=useState("");const[title,setTitle]=useState("");const[hospital,setHospital]=useState("");const[city,setCity]=useState("上海");const[specialties,setSpecialties]=useState("");const[bio,setBio]=useState("");const[credentials,setCredentials]=useState("");const[languages,setLanguages]=useState("中文, English");
const load=async()=>{const{data,error}=await supabase.from("doctors").select("*").order("created_at",{ascending:false});if(error)toast.error(error.message);else{const rows=(data??[])as Doctor[];const urls=await signedUrls("doctor-photos",rows.map(d=>d.photo_path));setDoctors(rows.map((d,i)=>({...d,photoUrl:urls[i]})))}};useEffect(()=>{if(user?.email?.toLowerCase()===ADMIN)void load()},[user]);if(authLoading)return <div/>;if(!user)return <Navigate to="/auth?next=/admin/doctors" replace/>;if(user.email?.toLowerCase()!==ADMIN)return <Navigate to="/" replace/>;
const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!name||!title||!hospital||!bio)return toast.error("请填写必填内容");setBusy(true);let photoPath:string|null=null;try{if(photo){photoPath=`${user.id}/${Date.now()}-${crypto.randomUUID()}.${photo.name.split('.').pop()}`;const{error}=await supabase.storage.from("doctor-photos").upload(photoPath,photo,{contentType:photo.type});if(error)throw error;}const{error}=await supabase.from("doctors").insert({name,title,hospital,city,specialties:specialties.split(/[,，]/).map(x=>x.trim()).filter(Boolean),bio,credentials:credentials||null,languages:languages||null,photo_path:photoPath,status:"published"});if(error)throw error;toast.success("医生资料已发布");setName("");setTitle("");setHospital("");setSpecialties("");setBio("");setCredentials("");setPhoto(null);await load()}catch(error){if(photoPath)await supabase.storage.from("doctor-photos").remove([photoPath]);toast.error(error instanceof Error?error.message:"发布失败")}finally{setBusy(false)}};
const remove=async(d:Doctor)=>{if(!confirm(`确定删除 ${d.name}？`))return;const{error}=await supabase.from("doctors").delete().eq("id",d.id);if(error)return toast.error(error.message);if(d.photo_path)await supabase.storage.from("doctor-photos").remove([d.photo_path]);setDoctors(x=>x.filter(i=>i.id!==d.id))};
return <div className="min-h-screen bg-muted/30"><header className="border-b bg-background"><div className="container h-16 flex items-center justify-between"><Link to="/upload" className="inline-flex gap-2 text-sm font-semibold"><ArrowLeft className="size-4"/>视频后台</Link><div className="flex items-center gap-4"><Link to="/admin/audit" className="text-sm text-muted-foreground hover:text-primary">审计报表</Link><span className="font-semibold">医生管理</span></div></div></header><main className="container py-8 grid lg:grid-cols-[420px_1fr] gap-8"><section className="rounded-3xl bg-card shadow-pop p-6 h-fit"><div className="flex gap-3 items-center mb-6"><Stethoscope className="text-primary"/><h1 className="font-display text-2xl">添加医生资料</h1></div><form onSubmit={submit} className="space-y-4"><div><Label>医生照片</Label><Input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></div><Field label="医生姓名 *" value={name} set={setName}/><Field label="职称 *" value={title} set={setTitle}/><Field label="医院/机构 *" value={hospital} set={setHospital}/><Field label="城市 *" value={city} set={setCity}/><Field label="擅长项目（逗号分隔）" value={specialties} set={setSpecialties}/><Field label="语言" value={languages} set={setLanguages}/><div><Label>医生介绍 *</Label><Textarea value={bio} onChange={e=>setBio(e.target.value)} rows={5}/></div><div><Label>资质与认证</Label><Textarea value={credentials} onChange={e=>setCredentials(e.target.value)} rows={3}/></div><Button disabled={busy} className="w-full rounded-full">{busy?<Loader2 className="animate-spin"/>:<><UploadCloud className="size-4 mr-2"/>发布医生</>}</Button></form></section><section><h2 className="font-display text-2xl mb-4">已添加医生（{doctors.length}）</h2><div className="grid sm:grid-cols-2 gap-4">{doctors.map(d=>{const photo=d.photoUrl??"";return <article key={d.id} className="rounded-2xl bg-card p-4 flex gap-4">{photo?<img src={photo} className="size-20 rounded-xl object-cover"/>:<div className="size-20 rounded-xl bg-muted"/>}<div className="min-w-0 flex-1"><Link to={`/doctors/profile/${d.id}`} className="font-semibold hover:text-primary">{d.name}</Link><p className="text-xs text-muted-foreground">{d.title} · {d.city}</p><Button variant="ghost" size="sm" className="text-destructive px-0 mt-2" onClick={()=>void remove(d)}><Trash2 className="size-4 mr-1"/>删除</Button></div></article>})}</div></section></main></div>}
const Field=({label,value,set}:{label:string;value:string;set:(v:string)=>void})=><div><Label>{label}</Label><Input value={value} onChange={e=>set(e.target.value)}/></div>;
