import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, BadgeCheck, Building2, Clock, Languages, Loader2, MapPin, Stethoscope } from "lucide-react";
import AsiaNavbar from "@/components/AsiaNavbar";
import Footer from "@/components/Footer";
import PageMeta from "@/components/PageMeta";
import { supabase } from "@/integrations/supabase/client";
import { signedUrl, signedUrls } from "@/lib/storage-urls";
import { formatCityTime, getCityTimezone } from "@/lib/timezones";

type Doctor = { id:string; name:string; title:string; hospital:string; city:string; specialties:string[]; bio:string; credentials:string|null; languages:string|null; photo_path:string|null };
type Video = { id:string; title:string; caption:string|null; storage_path:string; url?:string };
const ManagedDoctorDetail = () => {
  const { id="" } = useParams(); const [doctor,setDoctor]=useState<Doctor|null>(null); const [videos,setVideos]=useState<Video[]>([]); const [loading,setLoading]=useState(true); const [photo,setPhoto]=useState("");
  useEffect(()=>{(async()=>{const {data}=await supabase.from("doctors").select("*").eq("id",id).eq("status","published").maybeSingle();setDoctor(data as Doctor|null);if(data){setPhoto(await signedUrl("doctor-photos",(data as Doctor).photo_path));const r=await supabase.from("videos").select("id,title,caption,storage_path").eq("doctor_id",id).eq("status","published").order("created_at",{ascending:false});const rows=(r.data??[]) as Video[];const urls=await signedUrls("short-videos",rows.map(v=>v.storage_path));setVideos(rows.map((v,i)=>({...v,url:urls[i]})));}setLoading(false)})()},[id]);
  if(loading)return <div className="min-h-screen grid place-items-center"><Loader2 className="animate-spin"/></div>;
  if(!doctor)return <><AsiaNavbar/><main className="container py-24 text-center">医生资料不存在。<br/><Link to="/doctors" className="text-primary">返回医生列表</Link></main></>;
  return <><PageMeta title={`${doctor.name} | ${doctor.title}`} description={`${doctor.name}, ${doctor.title} at ${doctor.hospital} in ${doctor.city}.`} path={`/doctors/profile/${doctor.id}`} image={photo||undefined}/><div className="min-h-screen bg-background"><AsiaNavbar homeLinks={false}/><main className="container py-10 max-w-6xl"><Link to="/doctors" className="inline-flex gap-1 text-sm text-muted-foreground"><ArrowLeft className="size-4"/>全部医生</Link><section className="mt-6 rounded-3xl bg-card shadow-pop p-6 md:p-8 grid md:grid-cols-[260px_1fr] gap-8">{photo?<img src={photo} alt={doctor.name} className="w-full aspect-square rounded-3xl object-cover"/>:<div className="aspect-square rounded-3xl bg-muted grid place-items-center"><Stethoscope className="size-12 text-muted-foreground"/></div>}<div><span className="pill bg-accent text-accent-foreground"><BadgeCheck className="size-3.5"/>平台医生资料</span><h1 className="font-display text-4xl mt-4">{doctor.name}</h1><p className="text-muted-foreground mt-1">{doctor.title}</p><p className="flex gap-2 mt-4"><Building2 className="size-4 text-primary"/>{doctor.hospital}</p><p className="flex gap-2 mt-2"><MapPin className="size-4 text-primary"/>{doctor.city}</p><p className="flex gap-2 mt-2 text-sm text-muted-foreground"><Clock className="size-4 text-primary"/>{doctor.city}当地时间 {tz.offset}（{tz.label.zh}）· 现在约 {formatCityTime(tz,"zh")} — 预约咨询时间以此时区为准</p>{doctor.languages&&<p className="flex gap-2 mt-2"><Languages className="size-4 text-primary"/>{doctor.languages}</p>}<div className="flex flex-wrap gap-2 mt-5">{doctor.specialties.map(s=><span key={s} className="pill bg-accent">{s}</span>)}</div></div></section><section className="mt-10"><h2 className="font-display text-3xl">医生介绍</h2><p className="text-muted-foreground leading-relaxed mt-4 whitespace-pre-line">{doctor.bio}</p>{doctor.credentials&&<div className="rounded-2xl bg-muted/40 p-5 mt-6"><h3 className="font-semibold">资质与认证</h3><p className="text-sm text-muted-foreground mt-2 whitespace-pre-line">{doctor.credentials}</p></div>}</section><section className="mt-12"><h2 className="font-display text-3xl">该医生的短视频（{videos.length}）</h2>{videos.length===0?<p className="text-muted-foreground mt-4">暂时没有关联视频。</p>:<div className="flex gap-4 overflow-x-auto mt-6 pb-3">{videos.map(v=>{const src=v.url??"";return <article key={v.id} className="w-48 shrink-0"><video src={src} controls playsInline preload="metadata" className="w-full aspect-[9/16] object-cover rounded-2xl bg-black"/><h3 className="font-semibold mt-2">{v.title}</h3><p className="text-xs text-muted-foreground">{v.caption}</p></article>})}</div>}</section></main><Footer/></div></>;
};
export default ManagedDoctorDetail;
